-- MapMyJourney - Datos de Prueba Iniciales
-- NOTA: Todos los datos de prueba están comentados para evitar conflictos de secuencia
-- con nuevos registros de usuarios. La aplicación comenzará con una base de datos vacía.
-- Los usuarios pueden registrarse a través del formulario de signup.
